@startuml "Детализаци алгоритма производных раскладок"
skinparam monochrome true
' skinparam wrapWidth 300
skinparam defaultTextAlignment center
skinparam defaultFontSize 14
skinparam noteFontSize 14
start
:Исходная раскладка "ЙЦУКЕН";
repeat:Получение раскладки на вход алгоритма;
partition "Алгоритм производных раскладок" {
    :Сгенерировать случайное число X в интервале [1;3];
    if (X == 1) then (Да)
        :Сгенерировать случайное число Y в интервале [1;12];
        :Циклично сдвинуть Y колонку и получить все возможные варианты раскладок;
    else (Нет)
    endif
    if (X == 2) then (Да)
        :Сгенерировать случайное число Y в интервале [1;3];
        :Циклично сдвинуть Y ряд на левой половине раскладки и получить все возможные варианты раскладок;
    else (Нет)
    endif
    if (X == 3) then (Да)
        :Сгенерировать случайное число Y в интервале [1;3];
        :Циклично сдвинуть Y ряд на правой половине раскладки и получить все возможные варианты раскладок;
    else (Нет)
    endif
}
:Алгоритм оптимизации;
repeat while (Условие завершения алгоритма выполнено?) is (Нет) not (Да)
stop
@enduml